name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      environment: "${{ ( github.ref == 'refs/heads/main' && github.event_name == 'push' ) && 'production' || 'preview' }}"

  deploy-status:
    name: Deploy Status
    needs: [deploy]
    if: success() || failure()
    runs-on: ubuntu-latest
    env:
      STATUS: "${{ contains(needs.*.result, 'failure') && 'failed' || 'passed' }}"
      MESSAGE: "Latest deployment available at ${{ needs.deploy.outputs.url }}"
    steps:
      - name: Add preview URL to job summary
        run: |
          echo "${{ env.STATUS == 'failed' && 'Deploy Failed' || env.MESSAGE }}" >> $GITHUB_STEP_SUMMARY
      - name: Add preview URL to PR
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            "${{ env.STATUS == 'failed' && 'Deploy Failed' || env.MESSAGE }}"
      - name: Failing deploy
        if: ${{ env.STATUS == 'failed' }}
        run: exit 1

  smoke-test:
    name: Smoke Test
    needs: [deploy]
    uses: ./.github/workflows/playwright.yml
    with:
      url: ${{ needs.deploy.outputs.url }}
      tag: "@smoke"

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"
      - name: Install
        run: npm ci
      - name: Package
        run: npm run lint

  unit-test:
    name: Unit Test
    uses: ./.github/workflows/jest.yml

  component-test:
    name: Component Test
    uses: ./.github/workflows/playwright.yml
    with:
      url: ""
      tag: "@component"

  test-status:
    name: Test Status
    needs: [smoke-test, lint, unit-test, component-test]
    if: success() || failure()
    runs-on: ubuntu-latest
    env:
      STATUS: "${{ ( contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') ) && 'failed' || 'passed'}}"
    steps:
      - name: Add test status to PR
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          Append: true
          message: |
            Test suite ${{ env.STATUS }}
      - name: Failing deploy
        if: ${{ env.STATUS == 'failed' }}
        run: exit 1

  promote:
    name: Promote deployment to production
    needs: [test-status]
    if: ${{ github.ref == 'refs/heads/main' }}
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"
      - name: Alias build to production
        run: |
          npx vercel pull --yes --environment=production --token=${{ secrets.VERCEL_API_TOKEN }} --scope=${{ vars.VERCEL_SCOPE }}
          echo "$(npx vercel alias ${{ needs.deploy.outputs.url }} $DOMAIN --token=${{ secrets.VERCEL_API_TOKEN }} --scope ${{ vars.VERCEL_SCOPE }})" >> "$GITHUB_STEP_SUMMARY"
